name: Workflow para verificar novos commits
run-name: ${{ github.actor }} está enviando um novo commit
on: 
  push:
    branches:
      - develop
jobs:
  build-and-tests:
    runs-on: ubuntu-latest  
    steps: 
      - name: Clonando o repositório e trocando para a branch correta
        uses: actions/checkout@v4
        
      - name: Instalando o Node.js versão 21  
        uses: actions/setup-node@v3
        with:	
          node-version: '21'  

      - name: Instalando a dependência BATS globalmente
        run: npm install -g bats

      - name: Instalando dependências do projeto
        run: npm install

      - name: Executando testes
        run: npm run test

      - name: Executando testes de cobertura
        run: npm run test:coverage		

      - name: Rodando a aplicação
        run: npm start